services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --protocol http2
    env_file:
      - .env
    networks:
      - my-network
    depends_on:
      frontend:
        condition: service_started
    
  frontend:
    image: zen-garden-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - my-network
    hostname: zengarden
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

  backend:
    image: zen-garden-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - my-network
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - my-network
    restart: unless-stopped
    command: ["--quiet", "--logpath=/dev/null"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mongodb_data: 

networks:
  my-network:
    driver: bridge