version: '3.8'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --protocol http2
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - my-network
    depends_on:
      frontend:
        condition: service_started
    
  frontend:
    image: zen-garden-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_ENCRYPTION_KEY=${VITE_ENCRYPTION_KEY}
      - VITE_CLIENT_VERSION=${VITE_CLIENT_VERSION}
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
      - FRONTEND_URL=${FRONTEND_URL}
    networks:
      - my-network
    hostname: zengarden
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

  backend:
    image: zen-garden-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - BACKEND_URL=${BACKEND_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - FRONTEND_URL=${FRONTEND_URL}
    networks:
      - my-network
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - my-network
    restart: unless-stopped
    command: ["--quiet", "--logpath=/dev/null"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mongodb_data: 

networks:
  my-network:
    driver: bridge